-- Supabase schema for raw MQTT sensor packets
-- Run this in the Supabase SQL editor.

create table if not exists public.sensor_raw_records (
  id bigint generated by default as identity primary key,
  machine_id text not null,
  sensor text not null,
  value double precision not null,
  unit text not null,
  timestamp timestamptz not null,
  received_at timestamptz not null default now(),
  topic text,
  payload jsonb not null
);

create index if not exists sensor_raw_records_machine_id_idx
  on public.sensor_raw_records (machine_id);

create index if not exists sensor_raw_records_sensor_idx
  on public.sensor_raw_records (sensor);

create index if not exists sensor_raw_records_timestamp_idx
  on public.sensor_raw_records (timestamp desc);

alter table public.sensor_raw_records enable row level security;

-- Optional policy example:
-- create policy "Allow insert for service role"
-- on public.sensor_raw_records
-- for insert
-- to authenticated
-- with check (true);
