-- Supabase schema for aggregated MQTT sensor data
-- Run this in the Supabase SQL editor.

create table if not exists public.sensor_aggregates (
  id bigint generated by default as identity primary key,
  machine_id text not null,
  sensor text not null,
  unit text not null,
  window_size integer not null check (window_size > 0),
  kept_count integer not null check (kept_count > 0),
  mean_value double precision not null,
  min_value double precision not null,
  max_value double precision not null,
  window_start timestamptz not null,
  window_end timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists sensor_aggregates_machine_id_idx
  on public.sensor_aggregates (machine_id);

create index if not exists sensor_aggregates_sensor_idx
  on public.sensor_aggregates (sensor);

create index if not exists sensor_aggregates_created_at_idx
  on public.sensor_aggregates (created_at desc);

alter table public.sensor_aggregates enable row level security;

-- Optional policy examples:
-- If you insert from the backend using the service role key, RLS is bypassed.
-- If you later want anon-authenticated reads, add a policy like:
-- create policy "Allow read for authenticated users"
-- on public.sensor_aggregates
-- for select
-- to authenticated
-- using (true);
